#Assignment2 on numpy

In [113]:
#0.1. MANIPULATING EXISTING ARRAYS
#0.1.1 Load from a txt file
#importing numpy library
import numpy as np
#loading a text file using numpy
text_file=np.loadtxt('array_text.txt',dtype=int)
print('array is ; ')
#displayig loaded text file
print(text_file)

array is ; 
[[1 2 3 4]
 [5 6 7 8]
 [9 0 4 6]]


In [16]:
#0.1.2 Load from CSV file
import numpy as np
#loading a text file as csv using numpy
array=np.loadtxt('Book1.csv',delimiter=',', skiprows=1,dtype=int)
print('array is: ')
#displayig loaded csv file
print(array)

array is: 
[[2 6 0]
 [3 8 8]
 [4 9 4]]


In [99]:
#0.1.3 Make a list into an array
import numpy as np
def numpy_lib(arr,flag):
    """
    Function numpy_lib convert user input list into a user specified datatype and construct.
    Parameters:
    -arr(list):input list to be converted.
    -flag(str):input constraints.
    Returns:
    -Numpy array created from the user input list with user specified constraint.
    """
    if flag=='default':
        return np.array(arr,dtype=int)
    elif flag=='zeroes':
        return np.zeros(len(arr),dtype=int)
    elif flag=='ones':
        return np.ones(len(arr),dtype=int)
    elif flag=='identity':
        return np.eye(len(arr),dtype=int)
    else:
        return "Enter a valid constraint"

#user input list
input_list = input("Enter the numbers: ")
array_list = [int(element) for element in input_list.split()]
#user input flag constraints
flag_name = input("Enter a constraint default, zeroes, ones,identity: ")

#function call to convert to convery list into different datatype
result = numpy_lib(array_list, flag_name)

#displaying result
print(result)

Enter the numbers:  1 2 3 4 5 6 7 8 9
Enter a constraint default, zeroes, ones,identity:  zeroes


[0 0 0 0 0 0 0 0 0]


In [100]:
#0.2. MAKING ARRAY FROM SCRATCH
#0.2.1 Making Block diagonal arrays
import numpy as np
        
# Generate three random 3x3 matrices
matrix1=np.random.randint(100, size=(3, 3))
matrix2=np.random.randint(100, size=(3, 3))
matrix3=np.random.randint(100, size=(3, 3))

print("Matrix 1:")
print(matrix1)

print("Matrix 2:")
print(matrix2)

print("Matrix 3:")
print(matrix3)
#create a block diagonal matrix using np.block and stores it in block_diagonal_matrix
block_diagonal_matrix=np.block([[matrix1,np.zeros_like(matrix1),np.zeros_like(matrix1)],
                                 [np.zeros_like(matrix2),matrix2,np.zeros_like(matrix2)],
                                 [np.zeros_like(matrix3),np.zeros_like(matrix3),matrix3]])
#displaying the block diagoanl matrix
print("Block Diagonal Matrix is: ")
print(block_diagonal_matrix)

Matrix 1:
[[55 48 12]
 [94 98 90]
 [29 80 47]]
Matrix 2:
[[74 84 75]
 [28 56 90]
 [ 5 79 16]]
Matrix 3:
[[28 97 80]
 [45 23 99]
 [25 91 97]]
Block Diagonal Matrix is: 
[[55 48 12  0  0  0  0  0  0]
 [94 98 90  0  0  0  0  0  0]
 [29 80 47  0  0  0  0  0  0]
 [ 0  0  0 74 84 75  0  0  0]
 [ 0  0  0 28 56 90  0  0  0]
 [ 0  0  0  5 79 16  0  0  0]
 [ 0  0  0  0  0  0 28 97 80]
 [ 0  0  0  0  0  0 45 23 99]
 [ 0  0  0  0  0  0 25 91 97]]


In [64]:
#0.2.2 Off diagonal block matrix
import numpy as np
        
#Generate three random 3x3 matrices
matrix1 = np.random.randint(100, size=(3, 3))
matrix2 = np.random.randint(100, size=(3, 3))
matrix3 = np.random.randint(100, size=(3, 3))

print("Matrix 1:")
print(matrix1)

print("Matrix 2:")
print(matrix2)

print("Matrix 3:")
print(matrix3)
#create a off diagonal block matrix using np.block and stores it in block_diagonal_matrix
off_diagonal_block_matrix=np.block([[np.zeros_like(matrix1),matrix1,matrix1],
                                 [matrix2,np.zeros_like(matrix2),matrix2],
                                 [matrix3,matrix3,np.zeros_like(matrix3)]])
#displaying the block diagoanl matrix
print("Off Diagonal Block Matrix is: ")
print(off_diagonal_block_matrix)

Matrix 1:
[[67 16 98]
 [21 49 34]
 [80 54  3]]
Matrix 2:
[[ 4 75 17]
 [16 56 22]
 [69 64 74]]
Matrix 3:
[[35 92 36]
 [23 32 50]
 [37 84 70]]
Off Diagonal Block Matrix is: 
[[ 0  0  0 67 16 98 67 16 98]
 [ 0  0  0 21 49 34 21 49 34]
 [ 0  0  0 80 54  3 80 54  3]
 [ 4 75 17  0  0  0  4 75 17]
 [16 56 22  0  0  0 16 56 22]
 [69 64 74  0  0  0 69 64 74]
 [35 92 36 35 92 36  0  0  0]
 [23 32 50 23 32 50  0  0  0]
 [37 84 70 37 84 70  0  0  0]]


In [24]:
#0.2.3 Elements
import numpy as np

def serial_number_index(matrix,index):
    """
    Function serial_number_index calculates serial of given index of matrix using np.ravel_multi_index
    Parameters:
    -matrix:matrix of which serial is calculated
    -index:given index.
    """
    #initialize  variable in which serial of given index is calculated using np.ravel_multi_index
    serial_number=np.ravel_multi_index(index,matrix)
    return serial_number

def boolean_matrix(matrix):
    """
    Function boolean_matrix make a matrix of Boolean Values that has True in the place 
    where the entry is not equal to zero but it is False wherever the entry is zero.
    parameter:
    -matrix:given matrix.
    """
    #create a Boolean matrix, True where entry is not equal to zero, False where it is zero.
    return matrix!=0

#generate random matrix
matrix=np.random.randint(9,size=(3,4))
print("Matrix is: ")
print(matrix)

#user input for row and column indices
input_row=int(input("Enter the row index: "))
input_col=int(input("Enter the column index: "))
given_index=(input_row,input_col)

#function call and storing value of serial number
serial=serial_number_index(matrix.shape,given_index)
#displaying serial number
print("Serial number of", given_index, "is:", serial)

#function call and storing boolean matrix
bool_matrix=boolean_matrix(matrix)
#displayig boolean matrix
print("Boolean matrix is: ")
print(bool_matrix)


Matrix is: 
[[1 3 1 1]
 [2 2 3 3]
 [5 0 4 0]]


Enter the row index:  2
Enter the column index:  3


Serial number of (2, 3) is: 11
Boolean matrix is: 
[[ True  True  True  True]
 [ True  True  True  True]
 [ True False  True False]]


In [106]:
#0.2.4 Matrix Operations
import numpy as np
def flag_matrix(m,flag):
    """
    Fucntion flag_matrix checks matrix properties bsed on the given flag.
    Parameters:
    -m(numpy.ndarray):input matrix
    -flag(str):flag specifies the matrix property
    Returns:
    -bool:True if matrix satisfies the specified property otherwise False
    """
    #if flag given is symmetric,checks symmetric property of matrix.
    if flag=='symmetric':
        m_t=m.transpose()
        return np.allclose(m,m_t)
    #if flag given is anti-symmetric,checks anti-symmetric property of matrix.
    elif flag=='anti-symmetric':
        m_t=-m.transpose()
        return np.allclose(m,m_t)
    #if flag given is idempotent,checks idempotent property of matrix.
    elif flag=='idempotent':
        m2=m@m
        return np.allclose(m,m2)
    #if flag given is hermitian,checks hermitian property of matrix.
    elif flag=='hermitian':
        mh=m.conj().T
        return np.allclose(m,mh)
    #if flag given is unitary,checks unitary property of matrix.
    elif flag=='unitary':
        identity=np.eye(len(m),dtype=complex)
        product=np.dot(m.conj().T,m)
        return np.allclose(identity,identity)
    else:
        return "Enter a valid flag"

#sample input
#matrix=np.array([[1+2j,2,3],[4,5+1j,6],[7,8,9+3j]],dtype=complex)
rows=int(input("enter the number of rows"))
cols=int(input("enter the number of cols"))

#user input matrix
matrix = np.array([[complex(element) for element in input(f"Row {i + 1}: ").split()] for i in range(rows)])

#user input string
flag_string=input("Enter the constraints,(symmetric,anti-symmetric,idempotent,hermitian,unitary)")
print(matrix)

#function call and stores result
result=flag_matrix(matrix,flag_string)
#displaying result
print("Matrix follows the ",flag_string,"property: ",result)


enter the number of rows 3
enter the number of cols 3
Row 1:  1 2 3
Row 2:  4 5 6
Row 3:  7 8 9
Enter the constraints,(symmetric,anti-symmetric,idempotent,hermitian,unitary) unitary


[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]]
Matrix follows the  unitary property:  True


In [103]:
#0.2.5 Array Operations
import numpy as np
def oneD_to_2D_array(array):
    """
    Function oneD_to_2D_array reshapes 1D array into 2D arrayhaving 3 rows.
    Parameter:
    -array(list):user input 1d array
    Returns:
    -returns the 2D array having 3 rows.
    """
    #checks if length of matrix is multiple of 3
    if len(array)%3==0:
        #reshapes 1D array into 2D array having 3 rows
        new_2Darray=np.array(array).reshape(3,len(array)//3)
        return new_2Darray
    else:
        return "Length of 1D array should be multiple of 3"

#user input for 1D array
array=input("Enter the Elements for 1D array: ")
array_list=[int(element) for element in array.split()]

#function call and variable stores result
result=oneD_to_2D_array(array_list)

#displaying result
print(f"\n2D array is:\n{result} ")

Enter the Elements for 1D array:  1 2 3 4 5 6 7 8 9



2D array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]] 


In [35]:
#0.2.6 Avoiding element-wise comparison
import numpy as np
def check_elements_are_same_given_index(array):
    """
    Function check_elements_are_same_given_index Check if elements at 3n positions are same.
    Parameters:
    - array1 (list):input list of elements.
    """

    #checks if all elements at 3n positions are same as the 0th element
    same_elements=np.all(array[::3]==array[0])

    #displaying result
    if same_elements:
        print("Elements at 3n positions are same.")
    else:
        print("Elements at 3n positions are not same.")
        
#user input for 1D array
array=input("Enter the Elements for 1D array: ")
array_list=np.array([int(element) for element in array.split()])

#function call
check_elements_are_same_given_index(array_list)

Enter the Elements for 1D array:  1 2 3 1 2 3 1 2 3


Elements at 3n positions are same.


In [102]:
#0.3. EXPONENTIALS
#0.3.1 Exponential using numpy 
import numpy as np

#given matrix
matrix=np.array([[1,2],[3,4]])

#calculate the exponential of the matrix using numpy
e_matrix=np.exp(matrix)

#displaying result
print(f"\nExponentials of matrix using numpy:\n{e_matrix} ")




#EXPONENTIAL USING TAYLOR EXPANSION
def matrix_exponential_using_taylorseries(element,order):

    """
    Function matrix_exponential_using_taylorseries calculates matrix exponential using Taylor expansion up to order 3
    Parameters:
    - element(numpy.ndarray):input matrix.
    - order(int): Taylor expansion order.
    Returns:
    - numpy.ndarray:Matrix exponential using Taylor expansion.
    """

    #initialize matrix_expo as identity matrix
    matrix_expo=np.eye(element.shape[0])

    #start with the first expo_term as the identity matrix
    expo_term=np.eye(element.shape[0])

    #iterate through yhe taylor series expo_terms
    for i in range(1,order+1):
        #update expo_term by multiplying with the matrix and dividing by the iteration index i.
        expo_term=np.dot(expo_term,H)/i
        #accumulate the updated expo_term into matrix_expo
        matrix_expo+=expo_term
    return matrix_expo
#given matrix
H=np.array([[1,2],[3,4]])

#given order,to find exponential upto order 3 in taylor series
order=3

#function call to find exponential of matrix using taylor series and storing the result
final_result=matrix_exponential_using_taylorseries(H,order)

#displaying the result
print(f"\nExponential of matrix using taylor series is:\n{final_result} ")

#No,they are not same because as the order increases the Taylor series accumulates more terms, and the identity matrix is repeatedly multiplied and divided. 
#the accumlation of these terms contributes the growing difference between taylor expansion and numpy results


Exponentials of matrix using numpy:
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]] 

Exponential of matrix using taylor series is:
[[11.66666667 16.        ]
 [24.         35.66666667]] 


In [93]:
#0.3.2 Euler’s formula
import numpy as np

def validate_eulers_formula(matrix):
    """
    Function validate_eulers_formula validates Eulers formula for matrices: e^(iX) = cos(X) + i*sin(X).
    Parameters:
    - matrix (numpy.ndarray):input matrix.
    Returns:
    - numpy.ndarray:result of the validation.
    """
    # Extract the real and imaginary parts of the matrix
    real_num=np.real(matrix)
    img_num=np.imag(matrix)

    #calculates cos(x) and sin(x) using real part in cosine,sine and imaginary part in hyperbolic sine and cosine
    cos_x=np.cos(real_num)*np.cosh(img_num)
    sin_x=np.sin(real_num)*np.sinh(img_num)

    # Combine to get the matrix exponential using Euler's formula
    exp_result=cos_x+1j*sin_x

    return exp_result
#given input
matrix=np.array([[1,2],[3,4]])

#product of matrix and iota
matrix_iota=matrix*1j

#function call and stores result in variable result
result=validate_eulers_formula(matrix_iota)

#displaying result
print(result)


[[ 1.54308063+0.j  3.76219569+0.j]
 [10.067662  +0.j 27.30823284+0.j]]


In [112]:
import numpy as np
#0.4. BUSINESS MANAGEMENT

#0.4.1 Array creation
#Function to load the dataset from a CSV file using np.loadtxt
def load_dataset(file):
    data=np.loadtxt(file,delimiter=',')
    return data

#0.4.2 Monthwise
#Function to prepare monthly data from the loaded dataset
def prepare_monthly_data(data):
    #determine the number of columns in the original data
    num_columns=data.shape[1]

    #calculates the number of rows needed to have a multiple of 12
    num_rows=(data.shape[0] // 12)* 12  #round down to the nearest multiple of 12

    #reshape the data array to have 12 rows
    #2D is automatically calculated to preserve the total number of entries of the dataset
    monthly_data=data[:num_rows].reshape(12, -1, num_columns)
    return monthly_data

#0.4.3 A specific Month
#Function to extract monthly data for a specific month
def extract_monthly_data(monthly_data, month_number):
    if 1 <=month_number<=12:
        return monthly_data[month_number - 1, :, :]
    else:
        print("Invalid month number choose a month between 1 and 12.")

#0.4.4 Adding new rows
#Function to add a new row to the matrix
def add_new_row(matrix):
    #create a new row filled with zeros
    new_row=np.zeros((1, matrix.shape[1]))  
    return np.vstack((matrix, new_row))

#0.4.5Adding new people
#Function to add a new column to the matrix
def add_new_person(matrix):
    #create a new column filled with zeros
    new_column=np.zeros((matrix.shape[0], 1))  
    return np.hstack((matrix, new_column))

#0.4.6 Statistics
#Function to calculate total income, mean, and standard deviation
def calculate_statistics(data):
    total_income_all_people = np.sum(data)
    total_income_per_person=np.sum(data,axis=0) #axis=0 operation should be done on vertical axis
    mean_income_per_person=np.mean(data,axis=0) #axis=1 operation should be done on horizontal axis
    std_dev_income_per_person=np.std(data,axis=0)
    mean_income_day_wise=np.mean(data,axis=1)
    std_dev_income_day_wise=np.std(data,axis=1)
    
    print("\n#0.4.6:STATISTICS:")
    
    print(f"\n->a:Total income of all people: {total_income_all_people}")
    
    print(f"\n->b:Total income of each person:\n{total_income_per_person}")

    print(f"\n->c:Mean income of each Person:\n{mean_income_per_person}")

    print(f"\n->d:Standard Deviation of income of each Person:\n{std_dev_income_per_person}")

    print(f"\n->e:Mean income day wise:\n{mean_income_day_wise}")

    print(f"\n->f:Standard Deviation of income day wise:\n{std_dev_income_day_wise}")

#file name or path of the CSV file
file_name='salaries.csv'

#call the function to load the dataset
data=load_dataset(file_name)

#displaying the result
print(f"\n#0.4.1:First 10 rows of the loaded dataset:\n{data[:10]}")

#call the function to prepare monthly data
monthly_data = prepare_monthly_data(data)

#Display the monthly data
print(f"\n#0.4.2:Monthly data of 12 rows and each row is a 2D array:\n{monthly_data}")

#extracting data for the 7th month
selected_month_data=extract_monthly_data(monthly_data, 7)
print(f"\n#0.4.3:Data for Month 7:\n{selected_month_data}")

#adding a new row
new_matrix_with_row=add_new_row(selected_month_data)
print(f"\n#0.4.4:Matrix with a new row:\n{new_matrix_with_row}")

#adding a new person/column
new_matrix_with_person=add_new_person(selected_month_data)
print(f"\n#0.4.5:Matrix with a new person (column):\n{new_matrix_with_person}")

#calculating statistics
calculate_statistics(data)




#0.4.1:First 10 rows of the loaded dataset:
[[  1.   2.   3.   4.   5.]
 [432. 411. 438. 442. 465.]
 [466. 475. 412. 428. 423.]
 [429. 407. 469. 477. 434.]
 [483. 474. 468. 485. 425.]
 [437. 470. 478. 495. 450.]
 [417. 471. 467. 477. 437.]
 [402. 414. 473. 436. 483.]
 [457. 433. 485. 415. 461.]
 [410. 471. 483. 474. 433.]]

#0.4.2:Monthly data of 12 rows and each row is a 2D array:
[[[  1.   2.   3.   4.   5.]
  [432. 411. 438. 442. 465.]]

 [[466. 475. 412. 428. 423.]
  [429. 407. 469. 477. 434.]]

 [[483. 474. 468. 485. 425.]
  [437. 470. 478. 495. 450.]]

 [[417. 471. 467. 477. 437.]
  [402. 414. 473. 436. 483.]]

 [[457. 433. 485. 415. 461.]
  [410. 471. 483. 474. 433.]]

 [[420. 403. 438. 485. 433.]
  [470. 487. 407. 408. 401.]]

 [[486. 432. 451. 405. 456.]
  [438. 484. 413. 445. 411.]]

 [[461. 475. 493. 474. 400.]
  [451. 416. 415. 412. 475.]]

 [[478. 499. 421. 401. 421.]
  [452. 481. 498. 450. 413.]]

 [[406. 426. 497. 403. 462.]
  [498. 412. 416. 431. 461.]]

 [[451. 445. 4